apiVersion: apps/v1
kind: Deployment
metadata:
  name: bachelor-web
spec:
  replicas: 1 # Default, overskrives i overlays
  selector:
    matchLabels:
      app: bachelor-web
  template:
    metadata:
      labels:
        app: bachelor-web
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # Miljøvariabler der peger på databasen (indsættes via Kustomize)
        env:
        - name: DB_HOST
          value: postgres-svc