apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bachelor-dev-env
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zosodk/bachelor-gitops.git # Dit Repo
    targetRevision: main
    path: kubernetes/overlays/dev # Stien til DEV overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: bachelor-dev
  
  # Automatisk Sync Policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Opret namespace automatisk